apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: demo.paxel.ca
  namespace: demo
spec:
  secretName: demo.paxel.ca-tls
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: demo.paxel.ca
  dnsNames:
  - demo.paxel.ca